name: Deploy to Replicate

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Cog
        run: |
          sudo curl -o /usr/local/bin/cog -L https://github.com/replicate/cog/releases/latest/download/cog_linux_x86_64
          sudo chmod +x /usr/local/bin/cog

      - name: Login to Replicate
        run: |
          echo "${{ secrets.REPLICATE_CLI_TOKEN }}" | cog login --token-stdin

      - name: Push to Replicate
        run: |
          cog push r8.im/qt-kat/nadia-vision